#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the compareTriplets function below.
def compareTriplets(a, b):
    score_a = 0
    score_b = 0
    if(a[0] > b[0]):
        score_a += 1
    elif(a[0] < b[0]):
        score_b += 1

    if(a[1] > b[1]):
        score_a += 1
    elif(a[1] < b[1]):
        score_b += 1
    
    if(a[2] > b[2]):
        score_a += 1
    elif(a[2] < b[2]):
        score_b += 1

    return [score_a, score_b]
            


if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    a = list(map(int, input().rstrip().split()))

    b = list(map(int, input().rstrip().split()))

    result = compareTriplets(a, b)

    fptr.write(' '.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
