#!/bin/python3

import math
import os
import random
import re
import sys


# Complete the sockMerchant function below.
def sockMerchant(n, ar):

    #colors = np.zeros((101,1))
    colors = [0] * 101
    for i in range(n):
        colors[ar[i]-1] += 1
    temp = 0    
    for i in range(101):
        temp += math.floor(colors[i]/2)    
    
    return(temp)








if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    ar = list(map(int, input().rstrip().split()))

    result = sockMerchant(n, ar)

    fptr.write(str(result) + '\n')

    fptr.close()
