#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the staircase function below.
def staircase(n):
    for i in range(n):
        temp_str = ''
        for j in range(n-i-1):
            temp_str = temp_str + ' '
        for j in range(n-i-1,n):
            temp_str = temp_str + '#'
        print(temp_str)

if __name__ == '__main__':
    n = int(input())

    staircase(n)
